apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cpi-triage-ai-train
  annotations:
    scenarios.ai.sap.com/name: "CPI-Triage-AI"
    scenarios.ai.sap.com/description: "Train a simple CPI log classifier"
    executables.ai.sap.com/name: "Train CPI classifier"
    executables.ai.sap.com/description: "Scikit-learn (LR) with DictVectorizer"
    artifacts.ai.sap.com/cpidataset.kind: "dataset"
    artifacts.ai.sap.com/cpimodel.kind: "model"
  labels:
    scenarios.ai.sap.com/id: "cpi-triage-ai"
    ai.sap.com/version: "4.0"
spec:
  entrypoint: pipeline
  arguments:
    parameters:
      - name: TARGET_COLUMN
        value: "CUSTOM_STATUS"    # Mandatory in UI → use sentinels so code uses mounted artifacts (no boto3)
      - name: S3_DATA_URI
        value: "artifact://cpidataset"
      - name: S3_MODEL_URI
        value: "artifact://cpimodel"
      - name: AWS_DEFAULT_REGION
        value: "us-east-1"

  templates:
    - name: pipeline
      inputs:
        artifacts:
          - name: cpidataset
            path: /app/data/         # CSV will appear as /app/data/cpi_logs_500.csv
            optional: false
      outputs:
        artifacts:
          - name: cpimodel
            globalName: cpimodel
            path: /app/model/model.pkl      # single file → no .tgz
            archive: { none: {} }
          - name: cpivectorizer
            globalName: cpivectorizer
            path: /app/model/vectorizer.pkl # single file → no .tgz
            archive: { none: {} }
      container:
        image: docker.io/balakalyandocker/miltonc:cpi-triage-ai-train-v2   # bump tag if you rebuild
        command: ["/bin/sh","-c"]
        env:
          - name: TARGET_COLUMN
            value: "{{workflow.parameters.TARGET_COLUMN}}"
          - name: S3_DATA_URI
            value: "{{workflow.parameters.S3_DATA_URI}}"
          - name: S3_MODEL_URI
            value: "{{workflow.parameters.S3_MODEL_URI}}"
          - name: AWS_DEFAULT_REGION
            value: "{{workflow.parameters.AWS_DEFAULT_REGION}}"

          # Point directly to the file the artifact creates:
          - name: DATA_PATH
            value: "/app/data/cpi_logs_500.csv"

          - name: MODEL_DIR
            value: "/app/model"
          - name: MODEL_PATH
            value: "/app/model/model.pkl"
          - name: VEC_PATH
            value: "/app/model/vectorizer.pkl"
        args:
          - "python /app/src/train_cpi_btpcore.py"



