FROM python:3.11-slim
WORKDIR /app
COPY src/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY src/serve_cpi_btpcore.py ./src/
EXPOSE 8080
CMD ["uvicorn", "src.serve_cpi_btpcore:app", "--host", "0.0.0.0", "--port", "8080"]
